######################################
# Script defines project pipeline via series of actions
######################################

version: '3.0'

expectations:
  population_size: 30000

actions:

  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv
  
# Process data ----
  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data: output/data/data_processed.rds
        csv: output/data/data_processed.csv
        
# Select cohort ----
  data_selection:
    run: r:latest analysis/data_selection.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data: output/data/data_cohort.rds
        csv: output/data/data_cohort.csv
      moderately_sensitive:
        csv: output/data/flowchart.csv

 # Data properties ----      
  data_properties:
    run: r:latest analysis/data_properties.R output/data/data_cohort.rds output/data_properties
    needs: [data_selection]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_cohort*.txt
        
  # Table 1 ----
  table_1:
    run: r:latest analysis/table_1.R
    needs: [data_selection]
    outputs:
      highly_sensitive:
        data: output/tables/table1_redacted.rds
      moderately_sensitive:
        table: output/tables/table1_redacted.html
        
  # Cox models - dose-2 coverage ----
  cox_model:
    run: r:latest analysis/cox_model.R
    needs: [data_selection]
    outputs:
      highly_sensitive:
        data1: output/data/data_cox.rds
        data2: output/model/mod_strat_coxph_redacted.rds
        csv: output/data/data_cox.csv
      moderately_sensitive:
        csv: output/model/mod_strat_coxph_redacted.csv
        
  # Logistic models - dose-2 coverage ----
  logistic_model:
    run: r:latest analysis/logistic_model.R
    needs: [cox_model]
    outputs:
      highly_sensitive:
        data: output/model/mod_strat_logistic_redacted.rds
      moderately_sensitive:
        csv: output/model/mod_strat_logistic_redacted.csv

  # Coverage summaries ----
  vaccine_coverage:
    run: r:latest -e 'rmarkdown::render("analysis/vaccine_coverage.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/markdown")'
    needs: [data_selection, table_1, cox_model, logistic_model]
    outputs:
      moderately_sensitive:
        html: output/markdown/vaccine_coverage.html
        csv: output/tables/coverage_over_time_rounded.csv

  # Check session info for set of packages ----
  #session:
  #  run: r:latest -e 'rmarkdown::render("analysis/session.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/markdown")'
  #  needs: [data_selection]
  #  outputs:
  #    moderately_sensitive:
  #      html: output/markdown/session.html
