######################################
# Script defines project pipeline via series of actions
######################################

version: '3.0'

expectations:
  population_size: 100000

actions:

  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv
  
# Process data ----
  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data: output/data/data_processed.rds
        csv: output/data/data_processed.csv
        
 # Data properties ----      
  data_properties:
    run: r:latest analysis/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt
        
  # Table 1 ----
  table_1:
    run: r:latest analysis/table_1.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table: output/tables/table1*.html

  # Coverage summaries ----
  vaccine_coverage:
    run: r:latest -e 'rmarkdown::render("analysis/vaccine_coverage.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/markdown")'
    needs: [generate_study_population, data_process]
    outputs:
      moderately_sensitive:
        html: output/markdown/vaccine_coverage.html
        csv: output/data/coverage_over_time_redacted.csv

